# Generated by Django 5.1.2 on 2024-10-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('deluxe', 'Deluxe Room'), ('executive', 'Executive Suite'), ('standard', 'Standard Room')], max_length=50)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='room_images/')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of guests')),
                ('available', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(blank=True, to='core.amenity')),
            ],
        ),
    ]
